#!/bin/bash
set -e

# This is the recommended pre-commit hook when developing tiger.
# Copy it to .git/hooks/pre-commit to start using it.
# It will run automatically before every commit, and abort the commit
# if an error is found.

cargo fmt --check
cargo clippy -p ck3-tiger
cargo clippy -p utils
cargo doc -p tiger-lib --no-deps --document-private-items
cargo +1.88 check
