//! Giant enum for all the [`Item`] types in the game.

use std::fmt::{Display, Formatter};

use strum_macros::{EnumCount, EnumIter, IntoStaticStr};

/// "items" are all the things that can be looked up in the game databases.
/// Anything that can be looked up in script with a literal string key, or that's loaded into
/// tiger's database and needs a unique key, is an `Item`.
///
/// There is some overlap with scopes, for example "culture" is both an `Item` and a scope type,
/// but the difference is that scopes are runtime values while items are always strings.
///
/// For example if a trigger takes a culture *scope*, you could supply either `culture:german` or
/// `scope:target_culture`, while if a trigger takes a culture *item*, you would have to supply just
/// `german` and don't have the option of supplying something determined at runtime.
#[derive(Copy, Clone, Debug, PartialEq, Eq, IntoStaticStr, Hash, PartialOrd, Ord, EnumCount, EnumIter)]
#[strum(serialize_all = "snake_case")]
#[non_exhaustive]
// The item table is in several alphabetized sections. First the generic items, then items used by
// multiple games, then a section for each game.
//
// Each item is marked with a cfg clause for its game. This is not strictly necessary, but it helps
// prevent "leakage" between the games, where they accidentally use each other's item types.
#[rustfmt::skip] // having cfg and the variant on the same line is much more readable
pub enum Item {
    // Generic items used by all games and assumed to be there by the validators in
    // non-game-specific `data` modules.
    Accessory,
    AccessoryTag,
    AccessoryVariation,
    AccessoryVariationLayout,
    AccessoryVariationTextures,
    Achievement,
    AchievementGroup,
    Asset,
    BlendShape,
    CharacterInteraction,
    Coa,
    CoaColorList,
    CoaColoredEmblemList,
    CoaDesignerColorPalette,
    CoaDesignerColoredEmblem,
    CoaDesignerEmblemLayout,
    CoaDesignerPattern,
    CoaPatternList,
    CoaTemplate,
    CoaTemplateList,
    CoaTexturedEmblemList,
    Culture,
    CustomLocalization,
    Decision,
    Define,
    Directory,
    Dlc,
    DlcFeature,
    DlcName,
    EffectLocalization,
    Entity,
    Entry,
    Ethnicity,
    Event,
    EventNamespace,
    File,
    Font,
    Fontfiles,
    GameConcept,
    GameRule,
    GameRuleSetting,
    GeneAgePreset,
    GeneAttribute,
    GeneCategory,
    GovernmentType,
    GuiLayer,
    GuiTemplate,
    GuiType,
    LawGroup,
    Localization,
    MapEnvironment,
    MapMode,
    Modifier,
    Music,
    MusicPlayerCategory,
    NamedColor,
    OnAction,
    Pdxmesh,
    PortraitAnimation,
    PortraitCamera,
    PortraitEnvironment,
    PortraitModifierGroup,
    PortraitModifierPack,
    Province,
    Religion,
    ScriptedEffect,
    ScriptedGui,
    ScriptedList,
    ScriptedModifier,
    ScriptedRule,
    ScriptedTrigger,
    ScriptValue,
    Shortcut,
    Sound,
    Terrain,
    TextFormat,
    TextIcon,
    TextureFile,
    TriggerLocalization,
    WidgetName,

    // Items shared by more than one game
    Building,
    CasusBelli,
    Character,
    CharacterTemplate,
    Climate,
    Currency,
    DeathReason,
    Dna,
    EventTheme,
    HolySite,
    Language,
    Law,
    Message,
    Region,
    Situation,
    Trait,
    TutorialLesson,
    TutorialLessonChain,
    TutorialLessonStep,

    // Items for ck3
    AccoladeCategory,
    AccoladeIcon,
    AccoladeName,
    AccoladeParameter,
    AccoladeType,
    ActivityGroupType,
    ActivityIntent,
    ActivityLocale,
    ActivityOption,
    ActivityOptionCategory,
    ActivityPhase,
    ActivityPulseAction,
    ActivityState,
    ActivityType,
    AiWarStance,
    AgentType,
    Amenity,
    AmenitySetting,
    ArtifactBlueprint,
    ArtifactFeature,
    ArtifactFeatureGroup,
    ArtifactHistory,
    ArtifactRarity,
    ArtifactSlot,
    ArtifactSlotType,
    ArtifactTemplate,
    ArtifactType,
    ArtifactVisual,
    Bookmark,
    BookmarkGroup,
    BookmarkPortrait,
    BooleanHouseAspirationParameter,
    BooleanHouseHeadParameter,
    BooleanHouseRelationParameter,
    BuildingFlag,
    BuildingGfx,
    CasusBelliGroup,
    Catalyst,
    ChallengeCharacter,
    CharacterBackground,
    CharacterInteractionCategory,
    ClothingGfx,
    CoaGfx,
    CoaDynamicDefinition,
    CohesionLevelParameter,
    CombatEffect,
    CombatPhaseEvent,
    ConfederationType,
    ConnectionArrow,
    CouncilPosition,
    CouncilTask,
    Countermeasure,
    CountermeasureParameter,
    CourtPosition,
    CourtPositionTask,
    CourtSceneCulture,
    CourtSceneGroup,
    CourtSceneRole,
    CourtSceneSetting,
    CourtType,
    CourtierGuestManagement,
    CultureAesthetic,
    CultureCreationName,
    CultureEra,
    CultureEthos,
    CultureHeritage,
    CultureHistory,
    CultureParameter,
    CulturePillar,
    CultureTradition,
    CultureTraditionCategory,
    DangerType,
    DecisionGroup,
    DiarchyMandate,
    DiarchyParameter,
    DiarchyType,
    Doctrine,
    DoctrineBooleanParameter,
    DoctrineGroup,
    DoctrineParameter,
    DomicileBuilding,
    DomicileParameter,
    DomicileType,
    Dynasty,
    DynastyLegacy,
    DynastyPerk,
    EpidemicType,
    EpidemicDeathReason,
    EventBackground,
    EventEffect2d,
    EventTransition,
    Faction,
    Faith,
Rite,
Tenet,
    FaithIcon,
    FervorModifier,
    FlatMapStyle,
    Flavorization,
    Focus,
    GeneticConstraint,
    GovernmentFlag,
    GraphicalFaith,
    GraphicalUnitType,
    GreatProjectType,
    GuestInviteRule,
    GuestSubset,
    GuestSystem,
    HeadDetermination,
    HoldingParameter,
    HoldingType,
    HolySiteParameter,
    Hook,
    House,
    HouseAspiration,
    HouseRelationLevel,
    HouseRelationType,
    HouseUnity,
    HouseUnityParameter,
    HouseUnityStage,
    ImportantAction,
    Innovation,
    InnovationFlag,
    InnovationParameter,
    Inspiration,
    LawFlag,
    LeaseContract,
    LegendChapter,
    LegendChronicle,
    LegendProperty,
    LegendSeed,
    LegendType,
    LegitimacyFlag,
    LegitimacyType,
    Lifestyle,
    LineType,
    MartialCustom,
    MemoryCategory,
    MemoryType,
    MenAtArms,
    MenAtArmsBase,
    MessageFilterType,
    MessageGroupType,
    ModifierFormat,
    MottoInsert,
    Motto,
    NameEquivalency,
    NameList,
    Nickname,
    OpinionModifier,
    Perk,
    PersonalTenetFlag,
    PerkTree,
    PlayableDifficultyInfo,
    PointOfInterest,
    PoolSelector,
    PortraitType,
    PrisonType,
    PuppetAction,
    PuppetType,
    ProjectContribution,
    ProvinceEffect,
    ProvinceMapping,
    RaidIntent,
    Relation,
    RelationFlag,
    ReligionFamily,
    RewardItem,
    RulerObjectiveType,
    Scheme,
    SchemePulseAction,
    ScriptedAnimation,
    ScriptedCost,
    ScriptedIllustration,
    Secret,
    Sexuality,
    SituationCatalyst,
    SituationGroupType,
    SituationHistory,
    SituationParticipantGroup,
    SituationParticipantGroupParameter,
    SituationPhase,
    SituationPhaseParameter,
    SituationSubRegion,
    Skill,
    SpecialBuilding,
    SpecialGuest,
    SpiritualFulfillmentFlag,
    SpiritualFulfillmentType,
    Story,
    Struggle,
    StruggleHistory,
    StrugglePhase,
    StrugglePhaseParameter,
    SubjectContract,
    SubjectContractFlag,
    SubjectContractGroup,
    SubjectContractObligationLevel,
    SuccessionAppointment,
    SuccessionElection,
    Suggestion,
    TableStyle,
    TaskContractGroup,
    TaskContractReward,
    TaskContractType,
    TaxSlotObligation,
    TaxSlotType,
    Title,
    TitleHistory,
    TraitCategory,
    TraitFlag,
    TraitPortraitModifier,
    TraitTrack,
    TravelOption,
    UnitGfx,
    VassalStance,


}

/// Display items in `separated word case` for maximum friendliness.
///
/// Unfortunately there's no option for this in `strum` so we have to roll our own
/// by using `snake_case` and changing the `_` to a space.
impl Display for Item {
    fn fmt(&self, f: &mut Formatter) -> Result<(), std::fmt::Error> {
        let s: &'static str = self.into();
        write!(f, "{}", s.replace('_', " "))
    }
}

impl Item {
    /// Returns a path where items of this type are kept in the script files. Can be `""` for items
    /// that are built in.
    ///
    /// These paths are used both for the user in error reports, and to find the items when loading them.
    pub fn path(self) -> &'static str {
        #[allow(clippy::match_same_arms)]
        // These variants are in the same order as the Item enum declaration
        match self {
            Item::Accessory => "gfx/portraits/accessories/",
            Item::AccessoryTag => "gfx/portraits/accessories/",
            Item::AccessoryVariation => "gfx/portraits/accessory_variations/",
            Item::AccessoryVariationLayout => "gfx/portraits/accessory_variations/",
            Item::AccessoryVariationTextures => "gfx/portraits/accessory_variations/",
            Item::Achievement => "common/achievements/",
            Item::AchievementGroup => "common/achievement_groups.txt",
            Item::Asset => "gfx/models/",
            Item::BlendShape => "gfx/models/",
            Item::CharacterInteraction => "common/character_interactions/",
            Item::Coa => "common/coat_of_arms/coat_of_arms/",
            Item::CoaColorList => "common/coat_of_arms/template_lists/",
            Item::CoaColoredEmblemList => "common/coat_of_arms/template_lists/",
            Item::CoaDesignerColorPalette => "gfx/coat_of_arms/color_palettes/",
            Item::CoaDesignerColoredEmblem => "gfx/coat_of_arms/colored_emblems/",
            Item::CoaDesignerEmblemLayout => "gfx/coat_of_arms/emblem_layouts/",
            Item::CoaDesignerPattern => "gfx/coat_of_arms/patterns/",
            Item::CoaPatternList => "common/coat_of_arms/template_lists/",
            Item::CoaTemplate => "common/coat_of_arms/coat_of_arms/",
            Item::CoaTemplateList => "common/coat_of_arms/template_lists/",
            Item::CoaTexturedEmblemList => "common/coat_of_arms/template_lists/",
            Item::Culture => "common/culture/cultures/",
            Item::CustomLocalization => "common/customizable_localization/",
            Item::Decision => "common/decisions/",
            Item::Define => "common/defines/",
            Item::Dlc => "dlc_metadata/",
            Item::DlcFeature => "",
            Item::DlcName => "dlc_metadata/",
            Item::Directory => "",
            Item::EffectLocalization => "common/effect_localization/",
            Item::Entity => "gfx/models/",
            Item::Entry => "",
            Item::Ethnicity => "common/ethnicities/",
            Item::Event => "events/",
            Item::EventNamespace => "events/",
            Item::File => "",
            Item::Font => "fonts/",
            Item::Fontfiles => "fonts/",
            Item::GameConcept => "common/game_concepts/",
            Item::GameRule => "common/game_rules/",
            Item::GameRuleSetting => "common/game_rules/",
            Item::GeneAgePreset => "common/genes/",
            Item::GeneAttribute => "gfx/models/",
            Item::GeneCategory => "common/genes/",
            Item::GovernmentType => "common/governments/",
            Item::GuiLayer => "gui/",
            Item::GuiTemplate => "gui/",
            Item::GuiType => "gui/",
            Item::Localization => "localization/",
            Item::MapEnvironment => "gfx/map/environment/",
            Item::MapMode => "gfx/map/map_modes/",
            Item::Modifier => "common/modifiers/",
            Item::Music => "music/",
            Item::MusicPlayerCategory => "music/music_player_categories/",
            Item::NamedColor => "common/named_colors/",
            Item::OnAction => "common/on_action/",
            Item::Pdxmesh => "gfx/models/",
            Item::PortraitAnimation => "gfx/portraits/portrait_animations/",
            Item::PortraitCamera => "gfx/portraits/cameras/",
            Item::PortraitEnvironment => "gfx/portraits/environments/",
            Item::PortraitModifierGroup => "gfx/portraits/portrait_modifiers/",
            Item::PortraitModifierPack => "gfx/portraits/portrait_animations/",
            Item::Province => "map_data/definition.csv",
            Item::Religion => "common/religion/religion_types/",
            Item::ScriptedEffect => "common/scripted_effects/",
            Item::ScriptedGui => "common/scripted_guis/",
            Item::ScriptedList => "common/scripted_lists/",
            Item::ScriptedModifier => "common/scripted_modifiers/",
            Item::ScriptedRule => "common/scripted_rules/",
            Item::ScriptedTrigger => "common/scripted_triggers/",
            Item::ScriptValue => "common/script_values/",
            Item::Shortcut => "gui/shortcuts.shortcuts",
            Item::Sound => "",
            Item::Terrain => "common/terrain_types/",
            Item::TextFormat => "gui/",
            Item::TextIcon => "gui/",
            Item::TextureFile => "gfx/models/",
            Item::TriggerLocalization => "common/trigger_localization/",
            Item::WidgetName => "gui/",

            Item::Building => "common/buildings/",
            Item::CasusBelli => "common/casus_belli_types/",
            Item::Character => "history/characters/",
            Item::CharacterTemplate => "common/scripted_character_templates/",
            Item::Climate => "map_data/climate.txt",
            Item::Currency => "",
            Item::DeathReason => "common/deathreasons/",
            Item::Dna => "common/dna_data/",
            Item::EventTheme => "common/event_themes/",
            Item::HolySite => "common/religion/holy_site_types/",
            Item::Language => "common/culture/pillars/",
            Item::Law => "common/laws/",
            Item::LawGroup => "common/law_groups/",
            Item::Message => "common/messages",
            Item::Region => "map_data/geographical_regions/",
            Item::Situation => "common/situation/situations/",
            Item::Trait => "common/traits/",
            Item::TutorialLesson => "common/tutorial_lessons",
            Item::TutorialLessonChain => "common/tutorial_lesson_chains",
            Item::TutorialLessonStep => "common/tutorial_lessons",

            Item::AccoladeCategory => "common/accolade_types/",
            Item::AccoladeIcon => "common/accolade_icons/",
            Item::AccoladeName => "common/accolade_names/",
            Item::AccoladeParameter => "common/accolade_types/",
            Item::AccoladeType => "common/accolade_types/",
            Item::ActivityGroupType => "common/activities/activity_group_types/",
            Item::ActivityIntent => "common/activities/intents/",
            Item::ActivityLocale => "common/activities/activity_locales/",
            Item::ActivityOption => "common/activities/activity_types/",
            Item::ActivityOptionCategory => "common/activities/activity_types/",
            Item::ActivityPhase => "common/activities/activity_types/",
            Item::ActivityPulseAction => "common/activities/pulse_actions/",
            Item::ActivityState => "",
            Item::ActivityType => "common/activities/activity_types/",
            Item::AiWarStance => "common/ai_war_stances/",
            Item::AgentType => "common/schemes/agent_types/",
            Item::Amenity => "common/court_amenities/",
            Item::AmenitySetting => "common/court_amenities/",
            Item::ArtifactBlueprint => "common/artifacts/blueprints/",
            Item::ArtifactFeature => "common/artifacts/features/",
            Item::ArtifactFeatureGroup => "common/artifacts/feature_groups/",
            Item::ArtifactHistory => "",
            Item::ArtifactRarity => "",
            Item::ArtifactSlot => "common/artifacts/slots/",
            Item::ArtifactSlotType => "common/artifacts/slots/",
            Item::ArtifactTemplate => "common/artifacts/templates/",
            Item::ArtifactType => "common/artifacts/types/",
            Item::ArtifactVisual => "common/artifacts/visuals/",
            Item::Bookmark => "common/bookmarks/bookmarks/",
            Item::BookmarkGroup => "common/bookmarks/groups/",
            Item::BookmarkPortrait => "common/bookmark_portraits/",
            Item::BooleanHouseAspirationParameter => "common/house_aspirations/",
            Item::BooleanHouseHeadParameter => "common/house_aspirations/",
            Item::BooleanHouseRelationParameter => "common/house_relation_types/",
            Item::BuildingFlag => "common/buildings/",
            Item::BuildingGfx => "common/culture/cultures/",
            Item::CasusBelliGroup => "common/casus_belli_groups/",
            Item::Catalyst => "common/struggle/catalysts/",
            Item::ChallengeCharacter => "common/bookmarks/challenge_characters/",
            Item::CharacterBackground => "common/character_backgrounds/",
            Item::CharacterInteractionCategory => "common/character_interaction_categories/",
            Item::ClothingGfx => "common/culture/cultures/",
            Item::CoaGfx => "common/culture/cultures/",
            Item::CoaDynamicDefinition => "common/coat_of_arms/dynamic_definitions/",
            Item::CohesionLevelParameter => "common/confederation_types/",
            Item::CombatEffect => "common/combat_effects/",
            Item::CombatPhaseEvent => "common/combat_phase_events/",
            Item::ConfederationType => "common/confederation_types/",
            Item::ConnectionArrow => "common/connection_arrows/",
            Item::CouncilPosition => "common/council_positions/",
            Item::CouncilTask => "common/council_tasks/",
            Item::Countermeasure => "common/schemes/scheme_countermeasures/",
            Item::CountermeasureParameter => "common/schemes/scheme_countermeasures/",
            Item::CourtPosition => "common/court_positions/types/",
            Item::CourtPositionTask => "common/court_positions/tasks/",
            Item::CourtSceneCulture => "gfx/court_scene/scene_cultures/",
            Item::CourtSceneGroup => "gfx/court_scene/character_groups/",
            Item::CourtSceneRole => "gfx/court_scene/character_roles/",
            Item::CourtSceneSetting => "gfx/court_scene/scene_settings/",
            Item::CourtType => "common/court_types/",
            Item::CourtierGuestManagement => "common/courtier_guest_management/",
            Item::CultureAesthetic => "common/culture/aesthetics_bundles/",
            Item::CultureCreationName => "common/culture/creation_names/",
            Item::CultureEra => "common/culture/eras/",
            Item::CultureEthos => "common/culture/pillars/",
            Item::CultureHeritage => "common/culture/pillars/",
            Item::CultureHistory => "history/cultures/",
            // This is ugly since it isn't a path, but the path won't be used except in messages.
            Item::CultureParameter => "common/culture/ parameters blocks",
            Item::CulturePillar => "common/culture/pillars/",
            Item::CultureTradition => "common/culture/traditions/",
            Item::CultureTraditionCategory => "common/culture/traditions/",
            Item::DangerType => "",
            Item::DecisionGroup => "common/decision_group_types/",
            Item::DiarchyMandate => "common/diarchies/diarchy_mandates/",
            Item::DiarchyParameter => "common/diarchies/diarchy_types/",
            Item::DiarchyType => "common/diarchies/diarchy_types/",
            Item::Doctrine => "common/religion/doctrine_types/",
            Item::DoctrineBooleanParameter => "common/religion/doctrine_types/",
            Item::DoctrineGroup => "common/religion/doctrine_group_types/",
            Item::DoctrineParameter => "common/religion/doctrine_types/",
            Item::DomicileBuilding => "common/domiciles/buildings/",
            Item::DomicileParameter => "common/domiciles/buildings/",
            Item::DomicileType => "common/domiciles/types/",
            Item::Dynasty => "common/dynasties/",
            Item::DynastyLegacy => "common/dynasty_legacies/",
            Item::DynastyPerk => "common/dynasty_perks/",
            Item::EpidemicType => "common/epidemics/",
            Item::EpidemicDeathReason => "common/deathreasons/",
            Item::EventBackground => "common/event_backgrounds/",
            Item::EventEffect2d => "common/event_2d_effects/",
            Item::EventTransition => "common/event_transitions/",
            Item::Faction => "common/factions/",
            Item::Faith => "common/religion/faith_types/",
            Item::Rite => "common/religion/rite_types/",
            Item::Tenet => "common/religion/tenet_types/",
            Item::FaithIcon => "common/religion/faith_types/",
            Item::FervorModifier => "common/religion/fervor_modifiers/",
            Item::FlatMapStyle => "gfx/map/flat_map_styles/",
            Item::Flavorization => "common/flavorization/",
            Item::Focus => "common/focuses/",
            Item::GeneticConstraint => "common/traits/",
            Item::GovernmentFlag => "common/governments/",
            Item::GraphicalFaith => "common/religion/faith_types/",
            Item::GraphicalUnitType => "common/graphical_unit_types/",
            Item::GreatProjectType => "common/great_projects/types/",
            Item::GuestInviteRule => "common/activities/guest_invite_rules/",
            Item::GuestSubset => "common/activities/activity_types/",
            Item::GuestSystem => "common/guest_system/",
            Item::HeadDetermination => "common/culture/pillars/",
            Item::HoldingParameter => "common/holdings/",
            Item::HoldingType => "common/holdings/",
            Item::HolySiteParameter => "common/religion/holy_site_types/",
            Item::Hook => "common/hook_types/",
            Item::House => "common/dynasty_houses/",
            Item::HouseAspiration => "common/house_aspirations/",
            Item::HouseRelationLevel => "common/house_relation_types/",
            Item::HouseRelationType => "common/house_relation_types/",
            Item::HouseUnity => "common/house_unities/",
            Item::HouseUnityParameter => "common/house_unities",
            Item::HouseUnityStage => "common/house_unities/",
            Item::ImportantAction => "common/important_actions/",
            Item::Innovation => "common/culture/innovations/",
            Item::InnovationFlag => "common/culture/innovations/",
            Item::InnovationParameter => "common/culture/innovations/",
            Item::Inspiration => "common/inspirations/",
            Item::LawFlag => "common/laws/",
            Item::LeaseContract => "common/lease_contracts/",
            Item::LegendChapter => "common/legends/chronicles/",
            Item::LegendChronicle => "common/legends/chronicles/",
            Item::LegendProperty => "common/legends/chronicles/",
            Item::LegendSeed => "common/legends/legend_seeds/",
            Item::LegendType => "common/legends/legend_types/",
            Item::LegitimacyFlag => "common/legitimacy/",
            Item::LegitimacyType => "common/legitimacy/",
            Item::Lifestyle => "common/lifestyles/",
            Item::LineType => "gfx/lines/lines.lines",
            Item::MartialCustom => "common/culture/pillars/",
            Item::MemoryCategory => "common/character_memory_types/",
            Item::MemoryType => "common/character_memory_types/",
            Item::MenAtArms => "common/men_at_arms_types/",
            Item::MenAtArmsBase => "common/men_at_arms_types/",
            Item::MessageFilterType => "common/message_filter_types/",
            Item::MessageGroupType => "common/message_group_types/",
            Item::ModifierFormat => "common/modifier_definition_formats/",
            Item::MottoInsert => "common/dynasty_house_motto_inserts/",
            Item::Motto => "common/dynasty_house_mottos/",
            Item::NameEquivalency => "common/culture/name_equivalency/",
            Item::NameList => "common/culture/name_lists/",
            Item::Nickname => "common/nicknames/",
            Item::OpinionModifier => "common/opinion_modifiers/",
            Item::Perk => "common/lifestyle_perks/",
            Item::PersonalTenetFlag => "common/religion/tenet_types/",
            Item::PerkTree => "common/lifestyle_perks/",
            Item::PlayableDifficultyInfo => "common/playable_difficulty_infos/",
            Item::PointOfInterest => "common/travel/point_of_interest_types/",
            Item::PoolSelector => "common/pool_character_selectors/",
            Item::PortraitType => "common/portrait_types/",
            Item::ProjectContribution => "common/great_projects/types/",
            Item::ProvinceEffect => "gfx/map/province_effects/",
            Item::ProvinceMapping => "history/province_mapping/",
            Item::PrisonType => "",
            Item::PuppetAction => "common/puppets/actions/",
            Item::PuppetType => "common/puppets/types/",
            Item::RaidIntent => "common/raids/intents/",
            Item::Relation => "common/scripted_relations/",
            Item::RelationFlag => "common/scripted_relations/",
            Item::ReligionFamily => "common/religion/religion_family_types/",
            Item::RewardItem => "",
            Item::RulerObjectiveType => "common/ruler_objective_advice_types/",
            Item::SubjectContract => "common/subject_contracts/contracts/",
            Item::SubjectContractFlag => "common/subject_contracts/contracts/",
            Item::SubjectContractGroup => "common/subject_contracts/groups/",
            Item::SubjectContractObligationLevel => "common/subject_contracts/contracts/",
            Item::Scheme => "common/schemes/scheme_types",
            Item::SchemePulseAction => "common/schemes/pulse_actions",
            Item::ScriptedAnimation => "common/scripted_animations/",
            Item::ScriptedCost => "common/scripted_costs/",
            Item::ScriptedIllustration => "gfx/interface/illustrations/scripted_illustrations/",
            Item::Secret => "common/secret_types/",
            Item::Sexuality => "",
            Item::SituationCatalyst => "common/situation/catalysts/",
            Item::SituationGroupType => "common/situation/situation_group_types/",
            Item::SituationHistory => "history/situations/",
            Item::SituationParticipantGroup => "common/situation/situations/",
            Item::SituationParticipantGroupParameter => "common/situation/situations/",
            Item::SituationPhase => "common/situation/situations/",
            Item::SituationPhaseParameter => "common/situation/situations/",
            Item::SituationSubRegion => "common/situation/situations/",
            Item::Skill => "",
            Item::SpecialBuilding => "common/buildings/",
            Item::SpecialGuest => "common/activities/activity_types/",
            Item::SpiritualFulfillmentFlag => "common/spiritual_fulfillment/",
            Item::SpiritualFulfillmentType => "common/spiritual_fulfillment/",
            Item::Story => "common/story_cycles/",
            Item::Struggle => "common/struggle/struggles/",
            Item::StruggleHistory => "history/struggles/",
            Item::StrugglePhase => "common/struggle/struggles/",
            Item::StrugglePhaseParameter => "common/struggle/struggles/",
            Item::SuccessionAppointment => "common/succession_appointment/",
            Item::SuccessionElection => "common/succession_election/",
            Item::Suggestion => "common/suggestions/",
            Item::TableStyle => "gfx/map/table_styles/",
            Item::TaskContractGroup => "common/task_contracts/",
            Item::TaskContractReward => "common/task_contracts/",
            Item::TaskContractType => "common/task_contracts/",
            Item::TaxSlotObligation => "common/tax_slots/obligations",
            Item::TaxSlotType => "common/tax_slots/types",
            Item::Title => "common/landed_titles/",
            Item::TitleHistory => "history/titles/",
            Item::TraitCategory => "",
            Item::TraitFlag => "common/traits/",
            Item::TraitPortraitModifier => "gfx/portraits/trait_portrait_modifiers",
            Item::TraitTrack => "common/traits/",
            Item::TravelOption => "common/travel/travel_options/",
            Item::UnitGfx => "common/culture/cultures/",
            Item::VassalStance => "common/vassal_stances/",
        }
    }
}
